// <auto-generated />
using LanguageInstall.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageInstall.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113120100_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguageInstall.Data.Model.MainTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MainTables");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EnglishText = "First Name"
                        },
                        new
                        {
                            ID = 2,
                            EnglishText = "Last Name"
                        },
                        new
                        {
                            ID = 3,
                            EnglishText = "Submit"
                        },
                        new
                        {
                            ID = 4,
                            EnglishText = "Home"
                        },
                        new
                        {
                            ID = 5,
                            EnglishText = "Human Resource Management"
                        },
                        new
                        {
                            ID = 6,
                            EnglishText = "Leave Management"
                        },
                        new
                        {
                            ID = 7,
                            EnglishText = "Operation"
                        },
                        new
                        {
                            ID = 8,
                            EnglishText = "Leave Application Entry"
                        },
                        new
                        {
                            ID = 9,
                            EnglishText = "Company"
                        },
                        new
                        {
                            ID = 10,
                            EnglishText = "Employee ID"
                        },
                        new
                        {
                            ID = 11,
                            EnglishText = "Employee Name"
                        },
                        new
                        {
                            ID = 12,
                            EnglishText = "Designation"
                        },
                        new
                        {
                            ID = 13,
                            EnglishText = "Department"
                        },
                        new
                        {
                            ID = 14,
                            EnglishText = "Immediate Supervisor"
                        },
                        new
                        {
                            ID = 15,
                            EnglishText = "Head of Department"
                        },
                        new
                        {
                            ID = 16,
                            EnglishText = "Apply Leave Format"
                        },
                        new
                        {
                            ID = 17,
                            EnglishText = "Leave Type"
                        },
                        new
                        {
                            ID = 18,
                            EnglishText = "From"
                        },
                        new
                        {
                            ID = 19,
                            EnglishText = "Day(s)"
                        },
                        new
                        {
                            ID = 20,
                            EnglishText = "To"
                        },
                        new
                        {
                            ID = 21,
                            EnglishText = "Half Day"
                        },
                        new
                        {
                            ID = 22,
                            EnglishText = "First Half"
                        },
                        new
                        {
                            ID = 23,
                            EnglishText = "Second Half"
                        },
                        new
                        {
                            ID = 24,
                            EnglishText = "File Attachment"
                        },
                        new
                        {
                            ID = 25,
                            EnglishText = "Reason"
                        },
                        new
                        {
                            ID = 26,
                            EnglishText = "Leave Apply"
                        },
                        new
                        {
                            ID = 27,
                            EnglishText = "Select Dropdown Options"
                        },
                        new
                        {
                            ID = 28,
                            EnglishText = "--Select--"
                        },
                        new
                        {
                            ID = 29,
                            EnglishText = "--Select Apply Leave Format--"
                        },
                        new
                        {
                            ID = 30,
                            EnglishText = "Half Day Leave"
                        },
                        new
                        {
                            ID = 31,
                            EnglishText = "Full Day Leave"
                        },
                        new
                        {
                            ID = 32,
                            EnglishText = "Short Leave"
                        },
                        new
                        {
                            ID = 33,
                            EnglishText = "--Select--"
                        },
                        new
                        {
                            ID = 34,
                            EnglishText = "Button and Action Text"
                        },
                        new
                        {
                            ID = 35,
                            EnglishText = "Leave Apply"
                        },
                        new
                        {
                            ID = 36,
                            EnglishText = "Half Day"
                        },
                        new
                        {
                            ID = 37,
                            EnglishText = "Full Day"
                        },
                        new
                        {
                            ID = 38,
                            EnglishText = "Short Leave"
                        });
                });

            modelBuilder.Entity("LanguageInstall.Data.Model.Translation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainTableID")
                        .HasColumnType("int");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MainTableID");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("LanguageInstall.Data.Model.Translation", b =>
                {
                    b.HasOne("LanguageInstall.Data.Model.MainTable", "MainTable")
                        .WithMany("Translations")
                        .HasForeignKey("MainTableID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainTable");
                });

            modelBuilder.Entity("LanguageInstall.Data.Model.MainTable", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
